site_name: Robots Inside
site_url: https://robobe.github.io/
site_description: Guides, notes and useful stuff for learning robotics systems.
site_author: robobe

repo_url: https://github.com/robobe/new_blog


theme:
    name: material
    palette:
      primary: deep purple
    features:
    - content.code.copy
    - content.code.annotate
    # - toc.integrate
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand

    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button of the current search

nav:
  - Home: index.md
  - ROS: ROS/index.md
  - Simulation: Simulation/index.md
  - Robotics: Robotics/index.md
  - Programming: Programming/index.md
  - Embedded: Embedded/index.md
  - DevOps: DevOps/index.md
  - Other: Other/index.md
  - Projects: projects/index.md


plugins:
    - search
    - tags
    - include_uri
    - file_nav_links

markdown_extensions:
  - pymdownx.highlight:
      linenums: true  # Enables line numbers (optional)
      anchor_linenums: true
      use_pygments: true  # Ensures syntax highlighting
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex: # render math equations
      generic: true

extra_javascript:
  - https://unpkg.com/clipboard@2/dist/clipboard.min.js
  - assets/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  
extra_css:
  - extra.css