session_name: my_session
windows:
  - window_name: my_window
    layout: tiled
    suppress_history: false
    shell_command_before:
      - echo "before"
    panes:
      - shell_command: 
          - printf '\033]2;%s\033\\' 'pane1'
          - ./script1.sh  # Runs script1 in the first pane
        focus: true
      - shell_command:
          - printf '\033]2;%s\033\\' 'pane2'
          - ./script2.sh  # Runs script2 in the second pane
